### ISSUE TITLE
Slow when sending "null" values in writeRow

### ISSUE THREAD

**Issue by stenor99** [iliaal/php_excel#147]
#Hi,

I just downloaded php_excel and tried it with libxl 3.6.5.0 and while I enjoy it very much I have an issue with writeRow and "null" fields.

This completes in around 2 seconds (libxl license data removed):

    $book = new \ExcelBook('xxx', 'xxx', true);
    $book->setLocale('UTF-8');
    $sheet = $book->addSheet('test');
    $data = array('test', 'test', 'test');
    for($row = 0; $row < 100000; $row++) {
        $sheet->writeRow($row, $data);
    }
    $book->save("test-php.xlsx");

While this completes in around 10 seconds:

    $book = new \ExcelBook('xxx', 'xxx', true);
    $book->setLocale('UTF-8');
    $sheet = $book->addSheet('test');
    $data = array(null, 'test', 'test');
    for($row = 0; $row < 100000; $row++) {
        $sheet->writeRow($row, $data);
    }
    $book->save("test-php.xlsx");

If I add another null I am up to 30 seconds:

    $data = array(null, null, 'test');

I can surely check my data before calling writeRow but there may be some glitch here, unless I am missing something.

Thanks for your work!

Cheers,
Stefan

**Comment by johmue** [comment]
This is a valid problem. It is related to how php_excel handles write operations for ```null``` values. It iterates over all values of the row and creates a unique format for each ```null``` value before passing it to the libxl library because libxl expects a format to be given when writing blank values. This also bloats the size of the file btw.

If you never want to write ```null``` values (can be handy to clean cells) then you can easily add ```excel.skip_empty=1``` to your ```php.ini```file and php_excel will ignore ```null``` values entirely for write operations. If you set ```excel.skip_empty=2``` it will also ignore empty strings. So no write operation will be fired to libxl. This should result in less file size and faster writes.

Would be good to rewrite this part of php_excel to be more efficient.

**Comment by johmue** [comment]
just to make this complete, you can also use dummy formats...

```php
$book = new \ExcelBook('xxx', 'xxx', true);
$book->setLocale('UTF-8');
$sheet = $book->addSheet('test');

$dummyFormat= new \ExcelFormat($book); // create a format

$data = array(null, null, null);
for($row = 0; $row < 100000; $row++) {
    $sheet->writeRow($row, $data, 0, $dummyFormat);
}
$book->save("test-php.xlsx");
```

But be aware that it will really write formats into the cells and it will blow the file as well. You can check the last cell with ```CTRL+G``` in Excel and it will point you to cell ```C100000```.

**Comment by stenor99** [comment]
Thank you for the feedback.
After having identified the issue my solution was simply to avoid writing null values.

**Comment by iliaal** [comment]
You have 3 possible solutions (summary of pretty much what Johannes said):

A) (recommended) set the excel.skip_empty to 1 which will skip writing of NULL values, it'll make file smaller and writes faster.

B) Cast nulls to string, resulting in write of "" into a file which will be fast as it does not require a format to be set.

C) Avoid writing those values inside PHP
