### ISSUE TITLE
Writing a non-acceptance value causes weird error

### ISSUE THREAD

**Issue by davidsteinsland** [iliaal/php_excel#151]
```
 E_WARNING: ExcelSheet::write(): Failed to write cell in row 36, column 3 with error 'ok'
```

Should probably return an error saying that the variable type is not supported (for example if the variable is an object)

**Comment by johmue** [comment]
There can be plenty of reasons why a write operation fails. In general the extension should forward the php operation to libxl. In case an operation fails it should show you the cell index where the operation failed together with the last error message of libxl which seems to be "ok" in this case.

If you post a code snippet for reproduction it's maybe possible to check if the extension is handling your request not correct.

**Comment by davidsteinsland** [comment]
As I said, the argument is an object (PHP object…)

**Comment by johmue** [comment]
Ok, got it. Objects are not handled in the ```switch(...){...}``` block in the ```php_excel_write_cell(...)``` function so there is no call to libxl at all and therefore everything is fine from the libxl perspective which leads to the libxl error message of "ok". ```php_excel_write_cell(...)``` on the other hand returns ```false``` (since objects are not handled) which is then interpreted as a failed write operation. Adding a ```case IS_OBJECT: ...``` part should handle that but since it's not critical and my build system is broken I would leave it as is for the moment or you file a PR on your own and Ilia can review it then.

**Comment by Gerst20051** [comment]
was this not fixed in the php5 version? that commit was in the php7 branch.

**Comment by johmue** [comment]
This was fixed in PHP7 branch only - afaik

**Comment by Gerst20051** [comment]
thanks @johmue that's what i was thinking. maybe @iliaal can give some perspective as to whether or not the php5 version going to be maintained or updated going forward?

**Comment by johmue** [comment]
For my part I can say that I won't contribute to the PHP 5 branch anymore since all PHP 5 versions are outdated or close to (see http://php.net/supported-versions.php).
