### ISSUE TITLE
Feature request: lastDataColumn, lastDataRow

### ISSUE THREAD

**Issue by rts-barry** [iliaal/php_excel#173]
Sometimes an excel file has an out-lier cell with some style which returns a higher number than expected for lastRow, lastColumn.
This results in potentially high numbers of empty rows / columns.

A method that returns the last column and row that only looks at cell data would be nice as it will be possible to only fetch the data that is needed.

**Comment by johmue** [comment]
I think this is not a good approach since you have to define what a blank cell shall look like and you have to iterate over all cells (very slow). From my pov you should always eliminate empty cells in excel directly e.g. by build-in Excel Add-In "inquire" (https://support.office.com/en-us/article/Clean-excess-cell-formatting-on-a-worksheet-e744c248-6925-4e77-9d49-4874f7474738) or for older Excel versions custom Add-Ins like XsFormatCleaner (https://support.microsoft.com/en-us/kb/244435)
